### ISSUE TITLE
Lag when swiping from left to right

### ISSUE THREAD

**Issue by tom367** [vincurekf/NLMD-Native-like-Menu-Drawer#4]
I have noticed a small lag when opening the drawer by swiping from left to right.
This happens with Ionic 1.0.1. Is this something that can be improved?

Anyways awesome job on the drawer so far!

Thanks,

Tom

**Comment by tom367** [comment]
Solved it by using crosswalk, all animations are now very smooth

**Comment by vincurekf** [comment]
Glad to hear that, Tom! 
I see crosswalk is very interesting, thanks for mentioning :)
